---

- name: Debug info
  debug:
    msg:
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_SITEKEY = {{ QUINTIQ_SITEKEY }}
      - QUINTIQ_LICENSE_PATH = {{ QUINTIQ_LICENSE_PATH }}

- name: Set local variables
  set_fact:
    install_path: "{{ QUINTIQ_INSTALL_PATH }}"
    install_bin: "{{ QUINTIQ_INSTALL_PATH }}\\bin"
    sitekey: "{{ QUINTIQ_SITEKEY }}"
    serverkey_path: "{{ QUINTIQ_INSTALL_PATH }}\\server.key"
    license_path: "{{ QUINTIQ_LICENSE_PATH }}"

- name: New sitekey
  win_command: qk new server sitekey {{ sitekey }} {{ serverkey_path }}
  args:
    chdir: "{{ install_bin }}"
  ignore_errors: true

- name: Set sitekey of {{ sitekey }}
  win_command: qk set server sitekey {{ sitekey }}
  args:
    chdir: "{{ install_bin }}"
  ignore_errors: true

- name: License
  win_command: qk set server license {{ license_path }} --addrw --overwritelicense --overwritemappings
  args:
    chdir: "{{ install_bin }}"
  ignore_errors: true
