---
- hosts: QAE

  become: yes
  become_method: runas
  become_user: dsone\jlw1
  become_password: '=-09op[]":LKM<>?'
  
  tasks:
    - include_role:
        name: install_quintiq_software
        tasks_from: read_state2.yml

    - debug:
        var: quintiq_state