---
- hosts: QAE

  vars:
    - quintiq_version: "6420"
    - quintiq_zip_path: \\sdcvwdel40\QuintiqReleases\6420-all.zip

    - QUINTIQ_INSTALL_PATH: "D:\\quintiq{{ quintiq_version }}"    
    - QUINTIQ_MODELS_PATH: "D:\\jumbo\\models"
    - QUINTIQ_VAR_PATH: "D:\\jumbo\\var"
    - QUINTIQ_ETC_PATH: "D:\\jumbo\\etc"
  
  pre_tasks:
    - name: create {{ QUINTIQ_MODELS_PATH }} if not exists
      win_file: 
        path: "{{ QUINTIQ_MODELS_PATH }}"
        state: directory

    - name: create {{ QUINTIQ_VAR_PATH }} if not exists
      win_file: 
        path: "{{ QUINTIQ_VAR_PATH }}"
        state: directory
    
    - name: create {{ QUINTIQ_ETC_PATH }} if not exists
      win_file:
        path: "{{ QUINTIQ_ETC_PATH }}"
        state: directory          

    - name: Copy {{ quintiq_zip_path }} into tmp folder
      win_copy: 
        src: "{{ quintiq_zip_path }}"
        dest: "C:\\tmp"
        remote_src: true
      become: true
      become_method: runas
      become_user: dsone\jlw1      
      vars:
        ansible_become_password: =-09op[]":LKM<>?

  roles:
    - role: install_quintiq_core
      QUINTIQ_INSTALL_SRC_NAME: "{{ quintiq_version }}-all"
    