---
- hosts: QAE

  become: yes
  become_method: runas
  become_user: dsone\jlw1  

  vars:  
    - become_password: '=-09op[]":LKM<>?'
    - QUINTIQ_PROJECT: 'JUMBOHD'
    - QUINTIQ_VERSION: '6420'

  roles:
    
    - role: install_quintiq_software
      vars:
        QUINTIQ_SITEKEY: '162002'
        QUINTIQ_INSTALL_PATH: 'D:'
        QUINTIQ_MODEL: 
          SOURCE: 'Quicosolution642.qproject'
          NAME: 'Quicosolution'
        QUINTIQ_REPO:
          RELEASE_PATH: '\\sdcvwdel40\QuintiqReleases'
          LICENSE_PATH: '\\sdcvwdel40\QuintiqLicenses'
          MODEL_PATH: 'D:'
        QUINTIQ_WORKSPACE:
          MODELS_PATH: 'D:\jumbo\models'
          MODELS_PATH_CREATE: true   
          VAR_PATH: 'D:\jumbo\var'
          VAR_PATH_CREATE: true   

    - role: config_quintiq_component
      vars:
        QUINTIQ_COMPONENT: 'server'
        component_properties:
        - { key: 'serviceportgroup.serviceportgroup1.serviceport0.port', value: 7000 }
    
    - role: config_quintiq_component
      vars:
        QUINTIQ_COMPONENT: 'tce'
        component_properties:
        - { key: 'connectiongroup.connectiongroup1.connection0.protocol.port', value: 7000 }

- hosts: TCE

  become: yes
  become_method: runas
  become_user: dsone\jlw1  

  vars:  
    - become_password: '=-09op[]":LKM<>?'
    - QUINTIQ_PROJECT: 'JUMBOHD'
    - QUINTIQ_VERSION: '6420'

  roles:
    
    - role: install_quintiq_component
      vars:
        QUINTIQ_INSTALL_PATH: 'D:'
        QUINTIQ_REPO:
          RELEASE_PATH: '\\sdcvwdel40\QuintiqReleases'
          LICENSE_PATH: '\\sdcvwdel40\QuintiqLicenses'
          MODEL_PATH: 'D:'