---
- hosts: QAE
  
  pre_tasks:
    - name: create jumbo models if not exists
      win_file: 
        path: "D:\\jumbo\\models"
        state: directory

    - name: create jumbo var if not exists
      win_file: 
        path: "D:\\jumbo\\var"
        state: directory
    
    - name: create jumbo etc if not exists
      win_file:
        path: "D:\\jumbo\\etc"
        state: directory

  roles:
    - role: install_quintiq_core
      QUINTIQ_VERSION: "6420"
      QUINTIQ_INSTALL_PATH: "D:\\quintiq6420"
      QUINTIQ_MODELS_PATH: "D:\\jumbo\\models"
      QUINTIQ_ETC_PATH: "D:\\jumbo\\etc"
      QUINTIQ_VAR_PATH: "D:\\jumbo\\var"