---
- hosts: QAE

  vars:
    ROLE1_VAR1: "Playbook->vars"

  pre_tasks:

    - name: Debug info
      debug:
        msg:
          - env = {{ env }}
          # - pass = {{ vault_ansible_user_password }}

  roles:
    
    - role: role1
      ROLE1_VAR4: "Playbook->role1->vars"
      vars:
        ROLE1_VAR2: "Playbook->role1->vars"
        ROLE1_VAR3: "Playbook->role1->vars"
        
    - role: role2

- hosts: TCE

  tasks:
    
    - name: Ping Pong
      win_ping: