---
- hosts: QAE

  vars:
    ROLE1_VAR1: "Playbook->vars"

  pre_tasks:

    - name: Debug info
      debug:
        msg:
          - env = {{ env }}

  roles:
    
    - role: role1
      # vars:
      #   ROLE1_VAR1: "Playbook->role1->vars"
        
    - role: role2
      
