---
- hosts: QAE

  vars:
    - quintiq_version: "6420"
    - quintiq_sitekey: "162002"

    - quintiq_zip_src_path: \\sdcvwdel40\QuintiqReleases\6420-all.zip
    - quintiq_zip_path: "c:\\tmp\\6420-all.zip"

    - quintiq_license_src_path: \\sdcvwdel40\QuintiqLicenses\{{ ansible_env.COMPUTERNAME }}\{{ quintiq_sitekey }}\license.txt
    - quintiq_license_path: "c:\\tmp\\license_{{ quintiq_sitekey }}.txt"

    - QUINTIQ_MODELS_PATH: "D:\\jumbo\\models"
    - QUINTIQ_VAR_PATH: "D:\\jumbo\\var"
    - QUINTIQ_ETC_PATH: "D:\\jumbo\\etc"
      
  pre_tasks:
    - name: create "{{ QUINTIQ_MODELS_PATH }}" if not exists
      win_file: 
        path: "{{ QUINTIQ_MODELS_PATH }}"
        state: directory

    - name: create "{{ QUINTIQ_VAR_PATH }}" if not exists
      win_file: 
        path: "{{ QUINTIQ_VAR_PATH }}"
        state: directory
    
    - name: create "{{ QUINTIQ_ETC_PATH }}" if not exists
      win_file:
        path: "{{ QUINTIQ_ETC_PATH }}"
        state: directory          

    - name: Copy "{{ quintiq_zip_src_path }}" into tmp folder
      win_copy: 
        src: "{{ quintiq_zip_src_path }}"
        dest: "{{ quintiq_zip_path }}"
        remote_src: true
      become: true
      become_method: runas
      become_user: dsone\jlw1      
      vars:
        ansible_become_password: =-09op[]":LKM<>?

    - name: Copy "{{ quintiq_license_path }}" into tmp folder
      win_copy: 
        src: "{{ quintiq_license_src_path }}"
        dest: "{{ quintiq_license_path }}"
        remote_src: true
      become: true
      become_method: runas
      become_user: dsone\jlw1      
      vars:
        ansible_become_password: =-09op[]":LKM<>?

  post_tasks:
    - name: Cleanup temp zip file
      win_file:
        path: "{{ quintiq_zip_path }}"
        state: absent
      ignore_errors: true

    - name: Cleanup temp license file
      win_file:
        path: "{{ quintiq_license_path }}"
        state: absent
      ignore_errors: true

  roles:
    
    - role: install_quintiq_core
      QUINTIQ_INSTALL_SRC_NAME: "{{ quintiq_version }}-all"
      QUINTIQ_INSTALL_PATH: "D:\\quintiq{{ quintiq_version }}"

    - role: install_quintiq_license
      QUINTIQ_SITEKEY: "{{ quintiq_sitekey }}"
      QUINTIQ_LICENSE_PATH: "{{ quintiq_license_path }}"