---
- name: Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_PROPERTY_FILE = {{ QUINTIQ_PROPERTY_FILE }}

- name: Set local variables
  set_fact:
    property_file_path: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\etc\{{ QUINTIQ_PROPERTY_FILE }}'

- name: Local variables
  debug:
    msg:
      - "property_file_path: {{ property_file_path }}"

- name: Set properties values for file {{ QUINTIQ_PROPERTY_FILE }}
  win_lineinfile:
    path: '{{ property_file_path }}'
    regex: '^{{ item.key | regex_escape }}'
    line: '{{ item.key }}={{ item.value }}'
    insertafter: EOF
  loop: "{{ key_value_pairs }}"
  when: item.key is defined and item.value is defined
