---
- name: component.yml
  include_tasks: component.yml
  when: QUINTIQ_COMPONENT is defined and QUINTIQ_SUBCOMPONENT is not defined

- name: subcomponent.yml
  include_tasks: subcomponent.yml
  when: QUINTIQ_COMPONENT is defined and QUINTIQ_SUBCOMPONENT is defined