---
QUINTIQ_INSTALL_PATH: 'Q:'
env_tiger_pass: 'Tiger2023'

server_properties_default:
  - { key: 'arg.custom', value: 'StandAloneStorageState' }
  - { key: 'arg.internalstorageupgrade', value: 'true' }
  - { key: 'arg.logdays', value: 7 }
  - { key: 'arg.webserver', value: 'true' }
  - { key: 'arg.webserversoap', value: 'true' }
  - { key: 'connectiongroup.dbodbc1.connection0.protocol.securecommunication.authentication', value: 'Anonymous' }
  - { key: 'connectiongroup.dbodbc1.connection0.protocol.securecommunication.protocols', value: 'TLSv1.2' }
  - { key: 'connectiongroup.dbodbc1.connection0.protocol.securecommunication.strength', value: 'Normal' }
  - { key: 'connectiongroup.dbodbc1.connection0.protocol.streamtype', value: 'SECURESOCK_STREAM' }
  - { key: 'connectiongroup.dbodbc1.connection0.services', value: 'NOSERVICES' }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.audittrailenabled', value: 'true' }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.databaseenabled', value: 'false' }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.datasetstoreenabled', value: 'true' }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.datasetstoreislocal', value: 'false' }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.dbformat', value: 'Legacy' }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.driver', value: 'ODBC' }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.maxcolumnname', value: 128 }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.maxtablename', value: 128 }
  - { key: 'domainmodel.mdsstoragedefinitionmanager.parameters', value: '"/datasource={{ QUINTIQ_PROJECT }} /user=sa /owner=dbo"' }
  - { key: 'domainmodel.datasetrecovery.recovery.password', value: "{{ ('{{ QUINTIQ_PROJECT }}:{{ env_tiger_pass }}' | b64encode).decode('utf-8') }}" }
  - { key: 'serviceportgroup.serviceportgroup1.serviceport0.minimumsecurity', value: 'Anonymous' }
  - { key: 'serviceportgroup.serviceportgroup1.serviceport0.pem', value: 'QuintiqDHP.pem' }
  - { key: 'serviceportgroup.serviceportgroup1.serviceport0.protocols', value: 'TLSv1.2' }
  - { key: 'serviceportgroup.serviceportgroup1.serviceport0.tcpipversion', value: 'IPv4' }  
