---

- name: Set variables
  set_fact:
    quintiq:
      name: 'quintiq{{ buildver }}'
      path: 'D:\quintiq{{ buildver }}'
      zip_ref: '{{ buildver }}-all'
      zip_name: '{{ buildver }}-all.zip'
      zip_path: 'D:\public\{{ buildver }}-all.zip'
    temp_path: 'C:\tmp\quintiq{{ buildver }}'

- name: Check if {{ quintiq.path }} directory exists
  win_stat:
    path: '{{ quintiq.path }}'
  register: directory_check

- name: Unzip file to temporary directory C:\tmp\{{ quintiq.name }}
  win_unzip:
    src: '{{ quintiq.zip_path }}'
    dest: '{{ temp_path }}'
    creates: '{{ temp_path }}'
  when: not directory_check.stat.exists

- name: Move contents to destination directory
  win_shell: |
    Move-Item -Path '{{ temp_path }}\{{ quintiq.zip_ref }}' -Destination '{{ quintiq.path }}' -Force
  when: not directory_check.stat.exists

- name: Remove temporary directory (if it exists)
  win_shell: |
    Remove-Item -Path '{{ temp_path }}' -Recurse -Force -ErrorAction SilentlyContinue
  when: not directory_check.stat.exists
