---

- name: Set variables
  set_fact:
    zip_file:
      name: '{{ buildver }}-all'
      path: '{{ path_env.repository }}\{{ buildver }}-all.zip'
    temp_path: '{{ path_env.temp }}\quintiq{{ buildver }}'

- name: Check if {{ quintiq.path }} directory exists
  win_stat:
    path: '{{ quintiq.path }}'
  register: directory_check

- name: Unzip file to temporary directory {{ temp_path }}
  win_unzip:
    src: '{{ zip_file.path }}'
    dest: '{{ temp_path }}'
    creates: '{{ temp_path }}'
  when: not directory_check.stat.exists

- name: Move contents to destination directory
  win_shell: |
    Move-Item -Path '{{ temp_path }}\{{ zip_file.name }}' -Destination '{{ quintiq.path }}' -Force
  when: not directory_check.stat.exists

- name: Remove temporary directory (if it exists)
  win_shell: |
    Remove-Item -Path '{{ temp_path }}' -Recurse -Force -ErrorAction SilentlyContinue
  when: not directory_check.stat.exists
