---

- name: Debug info
  debug:
    msg:
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_INSTALL_SRC_PATH = {{ QUINTIQ_INSTALL_SRC_PATH }}
      - QUINTIQ_MODELS_PATH = {{ QUINTIQ_MODELS_PATH }}
      - QUINTIQ_ETC_PATH = {{ QUINTIQ_ETC_PATH }}
      - QUINTIQ_VAR_PATH = {{ QUINTIQ_VAR_PATH }}

- name: Set local variables
  set_fact:
    install_src: "{{ QUINTIQ_INSTALL_SRC_PATH }}\\{{ QUINTIQ_INSTALL_SRC_NAME }}"    
    install_dest: "{{ QUINTIQ_INSTALL_PATH }}"    
    install_bin: "{{ QUINTIQ_INSTALL_PATH }}\\bin"
    temp_path: "C:\\tmp"

- name: Check if "{{ install_dest }}" directory exists
  win_stat:
    path: "{{ install_dest }}"
  register: directory_check

- name: Unzip source file to "{{ temp_path }}\\{{ QUINTIQ_INSTALL_SRC_NAME }}"
  win_unzip:
    src: "{{ install_src }}.zip"
    dest: "{{ temp_path }}\\{{ QUINTIQ_INSTALL_SRC_NAME }}"
    creates: "{{ temp_path }}\\{{ QUINTIQ_INSTALL_SRC_NAME }}"
    rm: true
  when: not directory_check.stat.exists

- name: Move extracted source to destination "{{ install_dest }}"
  win_shell: |
    Move-Item -Path "{{ temp_path }}\\{{ QUINTIQ_INSTALL_SRC_NAME }}\\{{ QUINTIQ_INSTALL_SRC_NAME }}" -Destination "{{ install_dest }}" -Force
  when: not directory_check.stat.exists

- name: Remove "{{ temp_path }}\\{{ QUINTIQ_INSTALL_SRC_NAME }}"
  win_file: 
    path: "{{ temp_path }}\\{{ QUINTIQ_INSTALL_SRC_NAME }}"
    state: absent
  ignore_errors: true

- name: Check if the workspace file exists
  win_stat:
    path: "{{ install_dest }}\\default.qworkspace"
  register: workspace_file_info
  ignore_errors: true

- name: Create default workspace
  win_command: qk new workspace default
  args:
    chdir: "{{ install_bin }}"
  register: quintiq_workspace
  when: workspace_file_info.stat.exists is not defined or not workspace_file_info.stat.exists

- name: Set models path
  win_command: qk set workspace models="{{ QUINTIQ_MODELS_PATH }}"
  args:
    chdir: '{{ install_bin }}'
  when: QUINTIQ_MODELS_PATH is defined

- name: Set var path
  win_command: qk set workspace var="{{ QUINTIQ_VAR_PATH }}"
  args:
    chdir: '{{ install_bin }}'
  when: QUINTIQ_VAR_PATH is defined

- name: Set etc path
  win_command: qk set workspace etc="{{ QUINTIQ_ETC_PATH }}"
  args:
    chdir: '{{ install_bin }}'
  when: QUINTIQ_ETC_PATH is defined
