---
- name: component_default.yml - Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - component = {{ component }}

- name: component_default.yml - Set local variables
  set_fact:
    install_bin: '{{ QUINTIQ_INSTALL_PATH }}\\{{ QUINTIQ_PROJECT }}\\quintiq{{ QUINTIQ_VERSION }}\\bin'
    component_properties: "{{ lookup('vars', component + '_default' ) }}"

- name: component_default.yml - Local variables
  debug:
    msg:
      - "install_bin: {{ install_bin }}"

- debug:
    var: component_properties

- name: component_default.yml - Set default properties values
  win_command: qk set {{ component }} {{ item.key }}={{ item.value }}
  args:
    chdir: '{{ install_bin }}'
  loop: "{{ component_properties }}"
  when: item.key is defined and item.value is defined
