---
- name: component_properties_default.yml - Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - component = {{ component }}

- name: component_properties_default.yml - Set local variables
  set_fact:
    install_bin: '{{ QUINTIQ_INSTALL_PATH }}\\{{ QUINTIQ_PROJECT }}\\quintiq{{ QUINTIQ_VERSION }}\\bin'
    component_properties: "{{ lookup('vars', component + '_properties_default' ) }}"

- name: component_properties_default.yml - Local variables
  debug:
    msg:
      - "install_bin: {{ install_bin }}"

- name: component_properties_default.yml - Set default properties values
  win_command: qk set {{ item.0 }} {{ item.1.key }}={{ item.1.value }}
  args:
    chdir: '{{ install_bin }}'
  loop: "{{ component_properties }}"
  when: item.1.key is defined and item.1.value is defined
