---
- name: copy_model.yml - Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_REPO = {{ QUINTIQ_REPO }}
      - QUINTIQ_MODEL = {{ QUINTIQ_MODEL }}

- name: copy_model.yml - Set local variables
  set_fact:        
    copy_model_path: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\resources\models'
    copy_model_file: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\resources\models\{{ QUINTIQ_MODEL }}'

- name: copy_model.yml - Ensure the directory is present
  win_file:
    path: '{{ copy_model_path }}'
    state: directory
    
- name: copy_model.yml - Copy '{{ QUINTIQ_REPO.MODEL_FILE }}' into '{{ copy_model_file }}'
  win_copy: 
    src: '{{ QUINTIQ_REPO.MODEL_FILE }}'
    dest: '{{ copy_model_file }}'
    creates: '{{ copy_model_file }}'
    remote_src: true

- name: copy_model.yml - model file stat
  win_stat:
    path: copy_model_file
    get_checksum: true
  register: copy_model_file_rc


- debug:
    var: copy_model_file_rc.stat.checksum

- debug:
    var: copy_model_file