---
- name: Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT  }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION  }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_INSTALL_SRC_PATH = {{ QUINTIQ_INSTALL_SRC_PATH }}
      - QUINTIQ_INSTALL_SRC_NAME = {{ QUINTIQ_INSTALL_SRC_NAME }}
      - QUINTIQ_WORKSPACE = {{ QUINTIQ_WORKSPACE | default('undefined') }}
      - QUINTIQ_LICENSE = {{ QUINTIQ_LICENSE | default('undefined') }}

- name: Set local variables
  set_fact:        
    install_src: '{{ QUINTIQ_INSTALL_SRC_PATH }}\{{ QUINTIQ_INSTALL_SRC_NAME }}'
    install_prj: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}'
    install_dest: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq{{ QUINTIQ_VERSION }}'    
    install_bin: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq{{ QUINTIQ_VERSION }}\bin'
    temp_path: 'C:\tmp'
    
- name: Local variables
  debug:
    msg:
        - "install_src: {{ install_src }}"
        - "install_prj: {{ install_prj }}"
        - "install_dest: {{ install_dest }}"
        - "install_bin: {{ install_bin }}"
        - "temp_path: {{ temp_path }}"
        
- name: Check if {{ install_dest }} directory exists
  win_stat:
    path: '{{ install_dest }}'
  register: directory_check

- name: '{{ install_dest }} directory info'
  debug:
    var: directory_check

- name: Unzip source file to {{ temp_path }}\{{ QUINTIQ_INSTALL_SRC_NAME }}
  win_unzip:
    src: '{{ install_src }}.zip'
    dest: '{{ temp_path }}\{{ QUINTIQ_INSTALL_SRC_NAME }}'
    creates: '{{ temp_path }}\{{ QUINTIQ_INSTALL_SRC_NAME }}'
    # rm: true
  when: not directory_check.stat.exists

- name: Copy the extracted source to destination {{ install_dest }}
  win_copy:
    src: '{{ temp_path }}\{{ QUINTIQ_INSTALL_SRC_NAME }}\{{ QUINTIQ_INSTALL_SRC_NAME }}'
    dest: '{{ install_dest }}'
    remote_src: true
  when: not directory_check.stat.exists

- name: Copy etc folder to project path
  win_copy:
    src: '{{ install_dest }}\etc'
    dest: '{{ install_prj }}'
    remote_src: true
    force: false
  when: not directory_check.stat.exists

# - name: Move extracted source to destination {{ install_dest }}
#   win_shell: |
#     Copy-Item -Path '{{ temp_path }}\{{ QUINTIQ_INSTALL_SRC_NAME }}\{{ QUINTIQ_INSTALL_SRC_NAME }}' -Destination "{{ install_dest }}" -Force
#   when: not directory_check.stat.exists

- name: Remove extracted temp file {{ temp_path }}\{{ QUINTIQ_INSTALL_SRC_NAME }}
  win_file: 
    path: '{{ temp_path }}\{{ QUINTIQ_INSTALL_SRC_NAME }}'
    state: absent
  ignore_errors: true

- name: Check if the workspace file exists
  win_stat:
    path: '{{ install_dest }}\default.qworkspace'
  register: workspace_file_info
  ignore_errors: true

- name: Create default workspace
  win_command: qk new workspace default
  args:
    chdir: '{{ install_bin }}'
  register: quintiq_workspace
  when: >
    workspace_file_info.stat.exists is not defined or
    not workspace_file_info.stat.exists

- name: Set root path
  win_command: qk set workspace root="{{ install_prj }}"
  args:
    chdir: '{{ install_bin }}'
  when: >
    workspace_file_info.stat.exists is not defined or
    not workspace_file_info.stat.exists

- name: Set bin path
  win_command: qk set workspace bin="{{ install_bin }}"
  args:
    chdir: '{{ install_bin }}'
  when: >
    workspace_file_info.stat.exists is not defined or
    not workspace_file_info.stat.exists

- name: Update Quintiq state
  include_tasks: write_state.yml