---
- name: Debug info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT  }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION  }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_LICENSE = {{ QUINTIQ_LICENSE }}

- name: Set local variables
  set_fact:
    install_bin: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq{{ QUINTIQ_VERSION }}\bin'
    sitekey: '{{ QUINTIQ_LICENSE.SITEKEY }}'
    serverkey_path: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\site_{{ QUINTIQ_LICENSE.SITEKEY }}.key'
    license_path: '{{ QUINTIQ_LICENSE.FILE_PATH }}'

- name: New sitekey
  win_command: qk new server sitekey {{ sitekey }} {{ serverkey_path }}
  args:
    chdir: '{{ install_bin }}'
  ignore_errors: true

- name: Set sitekey of {{ sitekey }}
  win_command: qk set server sitekey {{ sitekey }}
  args:
    chdir: '{{ install_bin }}'
  ignore_errors: true

- name: License
  win_command: qk set server license {{ license_path }} --addrw --overwritelicense --overwritemappings
  args:
    chdir: '{{ install_bin }}'
  ignore_errors: true
