---
- name: license.yml - Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT  }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION  }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_SITEKEY = {{ QUINTIQ_SITEKEY }}

- name: license.yml - Set local variables
  set_fact:
    install_bin: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq{{ QUINTIQ_VERSION }}\bin'
    sitekey: '{{ QUINTIQ_LICENSE.SITEKEY }}'
    serverkey_path: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\site_{{ QUINTIQ_LICENSE.SITEKEY }}.key'
    license_path: '{{ QUINTIQ_LICENSE.FILE_PATH }}'

- name: license.yml - Check sitekey {{ serverkey_path }}
  win_command: qk get server sitekey
  args:
    chdir: '{{ install_bin }}'
  register: qk_sitekey
  ignore_errors: true 

- name: license.yml - New sitekey
  win_command: qk new server sitekey {{ sitekey }} {{ serverkey_path }}
  args:
    chdir: '{{ install_bin }}'
  ignore_errors: true
  when: qk_sitekey.rc == 1

- name: license.yml - Set sitekey of {{ sitekey }}
  win_command: qk set server sitekey {{ sitekey }}
  args:
    chdir: '{{ install_bin }}'
  ignore_errors: true
  when: qk_sitekey.rc == 1

- name: license.yml - Copy license.txt
  include_tasks: copy_license.yml
  when: qk_sitekey.rc == 1

- name: license.yml - License
  win_command: qk set server license {{ copy_license_file }} --addrw --overwritelicense --overwritemappings
  args:
    chdir: '{{ install_bin }}'
  ignore_errors: true
  when: qk_sitekey.rc == 1 and copy_license_file is defined
