---

- name: core.yml
  include_tasks: core.yml

- name: default_server_settings.yml
  include_tasks: default_server_settings.yml
  when: QUINIQ_DEFAULT_SERVER_SETTINGS

- name: default_server_settings.yml
  include_tasks: default_server_settings.yml
  when: QUINIQ_DEFAULT_TCE_SETTINGS

- name: workspace.yml
  include_tasks: workspace.yml
  when: QUINTIQ_WORKSPACE is defined

- name: license.yml
  include_tasks: license.yml
  when: QUINTIQ_SITEKEY is defined

- name: model.yml
  include_tasks: model.yml
  when: QUINTIQ_MODEL is defined