---

- name: core.yml
  include_tasks: core.yml

- name: workspace.yml
  include_tasks: workspace.yml
  when: QUINTIQ_WORKSPACE is defined

- name: license.yml
  include_tasks: license.yml
  when: QUINTIQ_SITEKEY is defined

- name: model.yml
  include_tasks: model.yml
  when: QUINTIQ_MODEL is defined