---
- name: model.yml - Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT  }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION  }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_MODEL = {{ QUINTIQ_MODEL }}

- name: model.yml - Set local variables
  set_fact:        
    install_bin: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq{{ QUINTIQ_VERSION }}\bin'
    model_checksum_file: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq_model.yml'

- name: model.yml - Local variables
  debug:
    msg:
        - "install_bin: {{ install_bin }}"  

- name: model.yml - Copy model source
  include_tasks: copy_model.yml

- name: model.yml - Read stored model checksum
  win_shell: Get-Content '{{ model_checksum_file }}'
  register: model_checksum
  ignore_errors: true
  when: copy_model_rc.stat.exists

- name: model.yml - Check if any changes
  set_fact:
    model_changed: "{{ copy_model_rc.stat.exists | default(false) and copy_model_rc.stat.checksum not in model_checksum.stdout }}"

- debug:
    msg:
      - "model_checksum: {{ model_checksum | default('') }}"
      - "copy_model_rc.stat.checksum: {{ copy_model_rc.stat.checksum }}"
      - "model_changed: {{ model_changed }}"

- name: model.yml - Install/Upgrade model from '{{ copy_model_rc.stat.path }}'
  win_command: qk new server model {{ copy_model_rc.stat.path }}
  args:
    chdir: '{{ install_bin }}'
  register: qk_model
  when: model_changed

- name: model.yml - Store model checksum
  win_copy:
    content: '{{ copy_model_rc.stat.checksum }}'
    dest: '{{ model_checksum_file }}'
  when: model_changed
  ignore_errors: true

- name: model.yml - Set active model
  win_command: qk set server model {{ QUINTIQ_MODEL.NAME }}
  args:
    chdir: '{{ install_bin }}'
  register: qk_model_active
  when: qk_model.changed
  ignore_errors: true

- name: model.yml - New configset [Common,qod,{{ ansible_env.COMPUTERNAME }}]
  win_command: qk new server configset [Common,qod,{{ ansible_env.COMPUTERNAME }}] --local
  args:
    chdir: '{{ install_bin }}'
  when: qk_model.changed
  ignore_errors: true

- name: model.yml - Set configset [Common,qod,{{ ansible_env.COMPUTERNAME }}]
  win_command: qk set server configset [Common,qod,{{ ansible_env.COMPUTERNAME }}]
  args:
    chdir: '{{ install_bin }}'
  register: qk_configset_set
  ignore_errors: true
  # when: qk_configset_new.changed

