---
- name: Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      
- set_fact:
    quintiq_state: ''

- name: Read Quintiq state into quintiq_state variable
  win_shell: get-content '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq.yml'
  register: temp_quintiq_state 

- name: Convert the YAML content to an Ansible variable
  set_fact:
    quintiq_state: '{{ temp_quintiq_state.stdout | from_yaml }}'
  when: temp_quintiq_state.stdout is defined

- name: Display the variable
  debug:
    var: quintiq_state