---
- name: read_serverkey.yml - Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT  }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION  }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_SITEKEY = {{ QUINTIQ_SITEKEY }}

- name: read_serverkey.yml - Set local variables
  set_fact:
    install_bin: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq{{ QUINTIQ_VERSION }}\bin'
    serverkey_path: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\site_{{ QUINTIQ_SITEKEY }}.key'

- name: read_serverkey.yml - Local variables
  debug:
    msg:
        - "install_bin: {{ install_bin }}"  

- name: read_serverkey.yml - Check sitekey {{ serverkey_path }}
  win_command: qk get server sitekey
  args:
    chdir: '{{ install_bin }}'
  register: quintiq_serverkey
  ignore_errors: true 