---
- name: Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      
- set_fact:
    quintiq_state: null

- name: Read Quintiq state into quintiq_state variable
  include_vars:
    file: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq.yml'
    name: quintiq_state
    remote_src: true

- name: Display the variable
  debug:
    var: quintiq_state