---
- name: Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      
- name: Read Quintiq state into quintiq_state variable
  win_shell: get-content '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq.yml'
  register: temp_quintiq_state 

- name: Convert the YAML content to an Ansible variable
  set_fact:
    quintiq_info: '{{ temp_quintiq_state.stdout | from_yaml }}'
  register: quintiq_state
  ignore_errors: true
  failed_when: temp_quintiq_state.stdout is not defined

- name: Display the variables
  debug:
    var:
      - quintiq_state
      - quintiq_info
    