---
- name: workspace.yml - Parameters info
  debug:
    msg:
      - QUINTIQ_PROJECT = {{ QUINTIQ_PROJECT  }}
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION  }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}
      - QUINTIQ_WORKSPACE = {{ QUINTIQ_WORKSPACE | default('undefined') }}

- name: workspace.yml - Set local variables
  set_fact:
    install_bin: '{{ QUINTIQ_INSTALL_PATH }}\{{ QUINTIQ_PROJECT }}\quintiq{{ QUINTIQ_VERSION }}\bin'
  debug:
    msg:
        - "install_bin: {{ install_bin }}"  

- name: workspace.yml - Set models path
  win_command: qk set workspace models="{{ QUINTIQ_WORKSPACE.MODELS_PATH }}"
  args:
    chdir: '{{ install_bin }}'
  when: >
    QUINTIQ_WORKSPACE is defined and
    QUINTIQ_WORKSPACE.MODELS_PATH is defined

- name: workspace.yml - Set var path
  win_command: qk set workspace var="{{ QUINTIQ_WORKSPACE.VAR_PATH }}"
  args:
    chdir: '{{ install_bin }}'
  when: >
    QUINTIQ_WORKSPACE is defined and
    QUINTIQ_WORKSPACE.VAR_PATH is defined

- name: workspace.yml - Create models path
  win_file:
    path: '{{ QUINTIQ_WORKSPACE.MODELS_PATH }}'
    state: directory
  when: >
    QUINTIQ_WORKSPACE is defined and
    QUINTIQ_WORKSPACE.MODELS_PATH is defined and
    QUINTIQ_WORKSPACE.MODELS_PATH_CREATE|bool

- name: workspace.yml - Create var path
  win_file:
    path: '{{ QUINTIQ_WORKSPACE.VAR_PATH }}'
    state: directory
  when: >
    QUINTIQ_WORKSPACE is defined and
    QUINTIQ_WORKSPACE.VAR_PATH is defined and
    QUINTIQ_WORKSPACE.VAR_PATH_CREATE|bool