---
- name: Parameters info
  debug:
    msg:
      - QUINTIQ_VERSION = {{ QUINTIQ_VERSION  }}
      - QUINTIQ_INSTALL_PATH = {{ QUINTIQ_INSTALL_PATH }}

- name: Write Quintiq state to a file
  win_copy:
    content: |
      quintiq:
        version: '{{ QUINTIQ_VERSION  }}'
        path: 'QUINTIQ_INSTALL_PATH'
    dest: 'C:\Quintiq\state.yml'